config/routes.rb
Spree::Core::Engine.routes.draw do
  # Add your extension routes here
  namespace :admin do
    resources :categories do
      collection do
        post :update_positions
      end
      resources :catalogs
    end

    resources :catalogs, only: [:index, :show] do
      collection do
        get :search
      end
    end
  end

  namespace :api, defaults: { format: 'json' } do
    resources :categories do
      member do
        get :jstree
      end
      resources :catalogs do
        member do
          get :jstree
        end
      end
    end

    resources :catalogs, only: [:index]
  end
end

app/models/spree/catalog.rb
class Spree::Catalog < Spree::Taxon
  belongs_to :category, foreign_key: :taxonomy_id, class_name: 'Spree::Category', inverse_of: :catalogs
end

app/models/spree/category.rb
class Spree::Category < Spree::Taxonomy
  # has_many :catalogs, foreign_key: :taxonomy_id, class_name: "Spree::Catalog", inverse_of: :category
  # has_one :root, -> { where parent_id: nil }, foreign_key: :taxonomy_id, class_name: "Spree::Catalog", dependent: :destroy
end

app/controllers/spree/admin/catalogs_controller.rb
module Spree
  module Admin
    class CatalogsController < Spree::Admin::BaseController
      respond_to :html, :json, :js
      def index
      end

      def search
        if params[:ids]
          @catalogs = Spree::Catalog.where(id: params[:ids].split(','))
        else
          @catalogs = Spree::Catalog.limit(20).ransack(name_cont: params[:q]).result
        end
      end

      def create
        @category = Category.find(params[:category_id])
        @catalog = @category.catalogs.build(params[:catalog])
        if @catalog.save
          respond_with(@catalog) do |format|
            format.json { render json: @catalog.to_json }
          end
        else
          flash[:error] = Spree.t('errors.messages.could_not_create_catalog')
          respond_with(@catalog) do |format|
            format.html { redirect_to @category ? edit_admin_category_url(@category) : admin_categories_url }
          end
        end
      end

      def edit
        @category = Category.find(params[:category_id])
        @catalog = @category.catalogs.find(params[:id])
        @permalink_part = @catalog.permalink.split("/").last
      end

      def update
        @category = Category.find(params[:category_id])
        @catalog = @category.catalogs.find(params[:id])
        parent_id = params[:catalog][:parent_id]
        new_position = params[:catalog][:position]

        if parent_id
          @catalog.parent = Catalog.find(parent_id.to_i)
        end

        if new_position
          @catalog.child_index = new_position.to_i
        end

        if params[:permalink_part]
          @catalog.permalink_part = params[:permalink_part].to_s
        end

        @catalog.assign_attributes(catalog_params)

        if @catalog.save
          flash[:success] = flash_message_for(@catalog, :successfully_updated)
        end

        respond_with(@catalog) do |format|
          format.html { redirect_to edit_admin_category_url(@category) }
        end
      end

      def destroy
        @catalog = Catalog.find(params[:id])
        @catalog.destroy
        respond_with(@catalog) { |format| format.json { render json: '' } }
      end

      private

      def catalog_params
        params.require(:catalog).permit(permitted_catalog_attributes)
      end
    end
  end
end

app/controllers/spree/admin/categories_controller.rb
module Spree
  module Admin
    class CategoriesController < ResourceController
      private

      def location_after_save
        if @category.created_at == @category.updated_at
          edit_admin_category_url(@category)
        else
          admin_categories_url
        end
      end
    end
  end
end

app/helpers/spree/base_helper.rb
module Spree
  module BaseHelper
    def plural_resource_name(resource_class)
    end

    def admin_breadcrumbs
       @admin_breadcrumbs ||= []
    end

    def admin_breadcrumb(*ancestors, &block)
      admin_breadcrumbs.concat(ancestors) if ancestors.present?
      admin_breadcrumbs.push(capture(&block)) if block_given?
    end
  end
end

app/views/spree/admin/catalogs/index.html.erb
<% content_for :table_filter_title do %>
  <%= Spree.t(:choose_a_catalog_to_sort_products_for) %>
<% end %>

<% content_for :table_filter do %>
  <div data-hook="admin_orders_index_search" class="columns six">
    <input type='text' id='taxon_id' />
  </div>
<% end %>

<div class='sixteen columns'>
  <div id='taxon_products' class='list-group'></div>
</div>

app/views/spree/admin/categories/_catalog.html.erb
<% if catalog.children.length != 0 %>
  <ul>
    <% catalog.children.each do |child| %>
      <li id="<%= child.id %>" rel="catalog">
        <a style="background-image: url(<%= child.icon.url %>);" href="#"><%= child.name %></a>
        <% if child.children.length > 0 %>
          <%= render :partial => 'catalog', :locals => { :catalog => child } %>
        <% end %>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/spree/admin/categories/_form.html.erb
<div data-hook="admin_inside_category_form" class="field align-center">
  <%= f.field_container :name do %>
    <%= f.label :name, class: 'required' %><br />
    <%= error_message_on :category, :name, :class => 'fullwidth title' %>
    <%= text_field :category, :name %>
  <% end %>
</div>

app/views/spree/admin/categories/_list.html.erb
<table class="index sortable" id='listing_categories' data-hook data-sortable-link="<%= update_positions_admin_categories_url %>">
  <colgroup>
    <col style="width: 10%">
    <col style="width: 75%">
    <col style="width: 15%">
  </colgroup>
  <thead>
    <tr data-hook="categories_header">
      <th class="no-border"></th>
      <th><%= Spree::Taxonomy.human_attribute_name(:name) %></th>
      <th class="actions"></th>
    </tr>
  </thead>
  <tbody>
    <% @categories.each do |category| %>
      <tr id="<%= spree_dom_id category %>" data-hook="categories_row" class="<%= cycle('odd', 'even')%>">
        <td class="no-border">
          <% if can?(:update_positions, Spree::Taxonomy) %>
            <span class="handle"></span>
          <% end %>
        </td>
        <td class="align-center"><%= category.name %></td>
        <td class="actions">
          <% if can?(:update, category) %>
            <%= link_to_edit category, :no_text => true %>
          <% end %>
          <% if can?(:destroy, category) %>
            <%= link_to_delete category, :no_text => true %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/spree/admin/categories/edit.erb
<% content_for :page_actions do %>
  <li>
    <%= button_link_to Spree.t(:add_catalog), spree.admin_categories_path, { class: 'add-taxon-button' } %>
  </li>
<% end %>

<%= form_for [:admin, @category] do |f| %>
  <fieldset class="no-border-top">
    <%= render :partial => 'form', :locals => { :f => f } %>
    <div class="filter-actions actions">
      <%= button Spree.t('actions.update') %>
      <%= button_link_to Spree.t('actions.cancel'), admin_categories_path %>
    </div>
  </fieldset>


  <div>
    <script>
      Spree.routes.category_path = "<%= spree.api_category_path(@category) %>";
      Spree.routes.category_catalogs_path = "<%= spree.api_category_catalogs_path(@category) %>";
      Spree.routes.admin_category_taxons_path = "<%= spree.admin_category_catalogs_path(@category) %>";
    </script>
    <div id="category_tree" class="tree" data-category-id="<%= @category.id %>"></div>
  </div>
<% end %>

app/views/spree/admin/categories/index.html.erb
<% admin_breadcrumb(link_to plural_resource_name(Spree::Product), spree.admin_products_path) %>
<% admin_breadcrumb(plural_resource_name(Spree::Category)) %>

<% content_for :page_actions do %>
  <% if can?(:create, Spree::Category) %>
    <li>
      <%= button_link_to Spree.t(:new_category), spree.new_admin_category_url, :id => 'admin_new_taxonomy_link' %>
    </li>
  <% end %>
<% end %>

<% if @categories.any? %>
<div id="list-categories" data-hook>
  <%= render 'list' %>
</div>
<% else %>
  <div class="alpha twelve columns no-objects-found">
    <%= render 'spree/admin/shared/no_objects_found',
                 resource: Spree::Category,
                 new_resource_url: new_object_url %>
  </div>
<% end %>

app/views/spree/admin/categories/new.html.erb
<% admin_breadcrumb(link_to plural_resource_name(Spree::Product), spree.admin_products_path) %>
<% admin_breadcrumb(link_to plural_resource_name(Spree::Category), spree.admin_categories_path) %>
<% admin_breadcrumb(Spree.t(:new_category)) %>

<% content_for :page_actions do %>
<% end %>

<%= form_for [:admin, @category] do |f| %>
  <%= render :partial => 'form', :locals => { :f => f } %>
  <fieldset class="no-border-top">
    <br>
    <div class="filter-actions actions" data-hook="buttons">
      <%= button Spree.t('actions.create') %>
    </div>
  </fieldset>
<% end %>

app/views/spree/admin/shared/_no_objects_found.html.erb
<%= Spree.t(:no_resource, resource: plural_resource_name(resource)) %>
<% if can? :create, resource %>
  <%= link_to Spree.t(:create_one), new_resource_url %>
<% end %>

app/views/spree/admin/shared/_product_sub_menu.html.erb
<ul class="admin-subnav" data-hook="admin_product_sub_tabs">
  <% if can? :admin, Spree::Product %>
    <%= tab :products, match_path: '/products' %>
  <% end %>
  <% if can? :admin, Spree::OptionType %>
    <%= tab :option_types, match_path: '/option_types' %>
  <% end %>
  <% if can? :admin, Spree::Property %>
    <%= tab :properties %>
  <% end %>
  <% if can? :admin, Spree::Prototype %>
    <%= tab :prototypes %>
  <% end %>
  <% if can? :admin, Spree::Category %>
    <%= tab :categories %>
  <% end %>
  <% if can? :admin, Spree::Catalog %>
    <%= tab :catalogs %>
  <% end %>
</ul>